train:
  _target_: src.datasets.LJSpeechDataset
  instance_transforms:
    get_spectrogram:
      _target_: src.transforms.wav_augs.MelSpectrogram
      config: 
        _target_: src.transforms.wav_augs.MelSpectrogramConfig
val:
  _target_: src.datasets.LJSpeechDataset
  limit: 55
  instance_transforms:
    get_spectrogram:
      _target_: src.transforms.wav_augs.MelSpectrogram
      config: 
        _target_: src.transforms.wav_augs.MelSpectrogramConfig
