defaults:
  - model: hifigan
  - discriminators: multidiscriminator
  - writer: cometml
  - metrics: example #none
  - datasets: ljspeech #here is the limit dataset
  - dataloader: example #batch size here
  - transforms: baseline
  - _self_

optimizer:
  cls: torch.optim.AdamW
  betas: [0.8, 0.99]
  weight_decay: 0.01
  lr: 2e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR # torch.optim.lr_scheduler.ExponentialLR learning rate updated everybach?
  gamma: 0.999
  step_size: ${trainer.epoch_len}

loss_function:
  discriminator:
    _target_: src.loss.DisLoss
  generator:
    _target_: src.loss.GANLoss
    lambda_ft: 2
    lambda_mel: 45



trainer:
  log_step: 250
  n_epochs: 40
  epoch_len: 3300
  device_tensors: ["spectrogram", "audio"] # which tensors should be on device (ex. GPU)
  resume_from: "checkpoint-epoch1(1).pth" # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  parallel_option: true  # Enable multi-GPU DataParallel training
  device_ids: null  # null for auto-detect all GPUs, or list like [0, 1] for specific GPUs
  override: False # if True, will override the previous run with the same name
  #monitor: "min val_WER_(Argmax)" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  monitor: "off"
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved_more"
  seed: 1
